# StepheyBot Music System - Beets Configuration
# Optimized for high-quality music library management

# Library and directory settings
directory: /mnt/hdd/media/music/library/
library: /home/th3tn/.config/beets/musiclibrary.db

# Import settings
import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /home/th3tn/.config/beets/import.log

# Path formatting - Artist/Album structure
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype:soundtrack: Soundtracks/$album/$track - $title

# Replace problematic characters in filenames
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

# MusicBrainz settings
musicbrainz:
    host: musicbrainz.org
    ratelimit: 1.0
    ratelimit_interval: 1.0

# Plugins configuration
plugins:
    - fetchart
    - embedart
    - duplicates
    - scrub
    - replaygain
    - lastgenre
    - web
    - info
    - lyrics
    - chroma
    - edit
    - convert
    - smartplaylist

# Artwork settings
fetchart:
    auto: yes
    cautious: true
    cover_names: cover folder album front art
    sources: filesystem coverart itunes amazon albumart
    store_source: yes
    high_resolution: yes

embedart:
    auto: yes
    ifempty: no
    maxwidth: 1000
    remove_art_file: no

# Duplicate detection
duplicates:
    checksum: ffmpeg
    copy: /home/th3tn/.config/beets/duplicates/
    move: no
    delete: no
    full: no

# ReplayGain for volume normalization
replaygain:
    auto: yes
    backend: ffmpeg
    overwrite: no
    targetlevel: 89

# Genre detection
lastgenre:
    auto: yes
    source: album
    fallback: Electronic
    canonical: yes
    count: 1
    min_weight: 10
    title_case: yes
    separator: ', '

# Web interface
web:
    host: 127.0.0.1
    port: 8337
    cors: yes
    cors_supports_credentials: yes
    reverse_proxy: no

# Lyrics fetching
lyrics:
    auto: yes
    sources: genius lyricwiki musixmatch
    fallback: ''
    force: no

# Audio fingerprinting
chroma:
    auto: yes

# File conversion settings
convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 4
    format: mp3
    formats:
        mp3: -ab {bitrate}k -ac 2 -ar 48000
        flac: -acodec flac
        ogg: -acodec libvorbis -ab {bitrate}k

# Smart playlists
smartplaylist:
    auto: yes
    playlist_dir: /mnt/hdd/media/music/playlists/
    forward_slash: no
    prefix: 'beets'

# UI settings
ui:
    color: yes
    length_diff_thresh: 10.0

# Match settings for better accuracy
match:
    strong_rec_thresh: 0.04
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0

# Logging
log: /home/th3tn/.config/beets/beets.log
verbose: 1

# Additional settings for StepheyBot integration
per_disc_numbering: no
original_date: no
artist_credit: no
