http:
    middlewares:
        securityHeaders:
            headers:
                browserXssFilter: true
                contentTypeNosniff: true
                frameDeny: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000

        dashboardAuth:
            basicAuth:
                users:
                    - "admin:$apr1$salt$hashedpassword"
